name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # Xiaomi
  build-xiaomi-12-lite-lineageos23-a16:
    name: "Build POCO X5 5G (LineageOS 23.2 A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-xiaomi-12-lite-lineageos23-a16.yml
    secrets: inherit
